name: 'Create Extension Zip file'
on:
   workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v4  

       - name: Setup node
         uses: actions/setup-node@v3
         with:
            node-version: 16.13.x
            cache: npm  
            
       - name: Install
         run: npm ci

       - name: Build
         env: 
            SECRECT_API_KEY: ${{ secrets.API_KEY }}
         run: npm run buildActions

       - name: Zip the output directory
         run: zip -r extension.zip dist
 
       - name: Upload Build Artifact
         uses: actions/upload-artifact@v2
         with:
           name: extension-zipped
           path: extension.zip